#################
#  Training Parameters
#
# Tip:  To set a boolean in yaml, write either True/False or On/Off. Both
#       choices correspond to python's True/False.
#
# For the parameters' description, see dwi_ml.training.parameter_description.
##################

sampling:
    batch:
        chunk_size: 256
        max_batch_size: 20000
        nb_subjects_per_batch: 1
        cycles: 2
    streamlines:
        processing:
            step_size: null
            compress: False
            normalize_directions: True
        data_augmentation:
            noise_size: 0.
            noise_variability: 0
            split_ratio: 0
            reverse_ratio: 0.5

training:
    learning_rate: 0.001
    weight_decay: 0.01
    epochs:
        max_epochs: 2
        patience: null
        max_batches_per_epoch: 10000

model:
    previous_dirs:
        nb_previous_dirs: 0
    neighborhood:
        sphere_radius: null
        grid_radius: null

memory:
    lazy: False
    cache_size: null
    use_gpu: True
    nb_cpu_workers: 0
    worker_interpolation: False
    taskman_managed: False

randomization:
    rng: 1234
